🐋 Agrega archivo Dockerfile
IslasGECI/ejemplo_para_martha pull request #1
Opened 2021-01-22 19:58 UTC by marthapaolajm

Vamos a empezar agregando este primer archivo de cinco

2021-01-26 19:46 UTC, islasfernando commented
en un :tomato: con @marthapaolajm, agregamos el Makefile y el analyses.json, por lo que este PR se podría usar para revisar la existencia de los 5 archivos. @marthapaolajm me ayudas por favor a actualizar el nombre y la descripción de este Pull Request, el nuevo nombre podría ser algo como:

🔧Agrega los 5 archivos

2021-01-28 18:16 UTC, MaritzaB requested changes
Hola Martha. ¡Muchas felicidades, ya tienes tres de los cinco archivos en tu repositorio de ejemplo!.
Te dejé algunas sugerencias para que se vea mejor y para darte algunas _pistas_ de como utilizamos el archivo _Makefile_.

Por favor tambien te pido que crees los dos archivos faltantes:

- [x] Un archivo en la raíz que se llame `README.md` 
- [ ] Un archivo que se llame `actions.yml`

Y como última tarea que trates de construir el contenedor en el que trabajarás.
Algunas de estas tareas te parecerán confusas, así que para realizarlas, no dudes en pedirnos ayuda 🙌.

2021-01-29 20:11 UTC, xwalls commented
@maritza 
Martha y yo tuvimos un tomate para agregar el github actions (actions.yml),
ya lo probamos en su repositorio y esta funcionando correctamente.
hasta ahorita tiene dos tareas como  "Hola mundo"  pero fue un trabajo honesto!
Excelente trabajo martha 🚀 💃

2021-01-29 20:25 UTC, xwalls requested changes
Hola @marthapaolajm
Muy bien hecho, te dejo mi revision! :)

2021-01-29 20:25 UTC, xwalls commented on .github/workflows/actions.yml
> +      - name: Corre varios comandos.
Hola! @marthapaolajm
puedes cambiar este paso que tenga el objetivo construir la image de docker?
```suggestion
      - name: Construye imagen
```

quiza tengas que cambiar la ejecucion del comando 
`run: docker build --tag cinco_archivos .`

2021-01-29 20:42 UTC, xwalls commented
gracias por aceptar la sugerencia martha!💃

2021-01-29 20:42 UTC, xwalls approved these changes

2021-01-29 20:44 UTC, marthapaolajm commented
> gracias por aceptar la sugerencia martha!woman_dancing

Hola Xavier!
Gracias a ti por las sugerencias🍻

2021-02-02 17:54 UTC, marthapaolajm commented
@islasfernando @xwalls  y @MaritzaB  Ya agregue los cinco archivos que me indicaron. Podrian por favor hacerme algunas sugerencias, si estan bien.  😳

2021-02-04 16:50 UTC, MaritzaB requested changes
Muchas felicidades Martha, a estamos a un pasito 🦶🏽 de terminar esta tarea 🙌🏽.
Aquí te dejo unos comentarios con repecto al README 😄 .

2021-02-04 16:50 UTC, MaritzaB commented on README.md
> +## Descripción
Hola @marthapaolajm, estuve checando algunos posts para poderte hacer una buena sugerencia para tu README. Me encontré con [este post](https://medium.com/@jacksonz666/readme-best-practices-7c9ad6c2303), que me pareció muy sencillo de entender y del cual podríamos seguir, por lo pronto y para este fin, contestar la primera pregunta que plantea:

> 1. What is this project trying to achieve? (A short description will be great.)

Parece que la sección **Descripción** de tu README pretende contestar la primera pregunta, así que vamos bien :raised_hands:.
Ahora tratemos de mejorar la descripción :alien:. De [este post](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project), encontré lo siguiente con respecto a la introducción:

> Introduction is like a summary. It shouldn't be too long as we don't want to read an essay on a project. We should describe in an interesting manner what's the project aim. Two or three sentences are enough in case of a small project.

2021-02-04 16:50 UTC, MaritzaB commented on README.md
> +En este repositorio se agregaron cinco archivos, los cuales son: README.md, Makefile, Dockerfile, analyses.json y actions.yml, con el objetivo de aprender a usar las herramientas de GitHub y GitKrake
Con lo dicho en lo anterior, creo que convendría que en este párrafo explicaras de manera más general para qué es este repositorio, talvez algo como:

>  Este repositorio fue creado con el fin de documentar mi pvvc durante la estancia en GECI (
> En el primer reporte de este repositorio "nuestras herramientas" describo las herramientas que usamos en el equipo de ciencia de datos, como: ..., ..., ...

2021-02-04 16:50 UTC, MaritzaB commented on README.md
> +En este repositorio se agregaron cinco archivos, los cuales son: README.md, Makefile, Dockerfile, analyses.json y actions.yml, con el objetivo de aprender a usar las herramientas de GitHub y GitKrake
He visto en otros repositorios que ponen una sección de:
## Tecnologías usadas
Tal vez en una sección así podamos poner lo que escribiste ahí arriba:

> En este repositorio se agregaron cinco archivos, los cuales son: README.md, Makefile, Dockerfile...

2021-02-05 17:21 UTC, marthapaolajm commented on README.md
> +En este repositorio se agregaron cinco archivos, los cuales son: README.md, Makefile, Dockerfile, analyses.json y actions.yml, con el objetivo de aprender a usar las herramientas de GitHub y GitKrake
Hola @MaritzaB, muchas gracias por  tus sugerencias, ya mejore el README con los comentarios que me hiciste 🎉 . Si gustas checarlo, para ver que no se me haya pasado nada 😳.

2021-02-05 17:23 UTC, MaritzaB commented on README.md
> +En este repositorio se agregaron cinco archivos, los cuales son: README.md, Makefile, Dockerfile, analyses.json y actions.yml, con el objetivo de aprender a usar las herramientas de GitHub y GitKrake
Claro Martha, por favor no olvides picarle en el botoncito de arriba para solicitar revisión nuevamente 😉.
![image](https://user-images.githubusercontent.com/56838850/107067223-d701b980-6793-11eb-80c7-be889bd42562.png)

2021-02-05 19:23 UTC, xwalls commented on Makefile
> +define checkDirectories
@islasfernando @MaritzaB
aqui se esta definiendo checkDirectories pero no se esta usando,
alguien sabe para que servira?

2021-02-08 16:30 UTC, islasfernando commented on Makefile
> +define checkDirectories
@xwalls @marthapaolajm se puede borrar por ahora

2021-02-08 23:30 UTC, MaritzaB requested changes
🙌 Pues ya casi queda esto de los 5 archivos @marthapaolajm. Sólo te dejé un comentario relacionado con la retroalimentación que dió el equipo el viernes de la semana pasada ✌🏽.

2021-02-08 23:30 UTC, MaritzaB commented on README.md
> +En este repositorio se agregaron cinco archivos, los cuales son: README.md, Makefile, Dockerfile, analyses.json y actions.yml, con el objetivo de aprender a usar las herramientas de GitHub y Git Krak
Hola Martha, ¿qué te parece si en esta sección ponemos sólo la lista de los archivos que se agregaron al repo, y la descripción la agregamos al reporte de _nuestras herramientas_ que estás haciendo?

```suggestion
En este repositorio se agregaron cinco archivos, los cuales son: 

1. README.md
2. Makefile
3. Dockerfile
4. analyses.json 
5. actions.yml 

```

2021-02-09 18:47 UTC, marthapaolajm commented on Makefile
> +define checkDirectories
@islasfernando @xwalls  Entonces borro las lineas 5,6 y 7, o las dejo por si se utilizan mas a delante?

2021-02-09 18:49 UTC, islasfernando commented on Makefile
> +define checkDirectories
Sí porfavor bórralas @marthapaolajm, las agregamos cuando se ocupen

2021-02-10 16:51 UTC, MaritzaB approved these changes
Listo @marthapaolajm, se ve muy bien 😄 🙌🏽 . Felicidades por tu primer _Pull Request_ aprobado 🎊🎉

2021-02-10 16:52 UTC, merged