Reporte nuestras herramientas :page_facing_up:
IslasGECI/ejemplo_para_martha pull request #2
Opened 2021-02-11 19:22 UTC by marthapaolajm

En este Pull request, se revisara nuestras herramientas

- [ ] github actions genera el reporte

- [ ] Nomenclatura dentro del .tex o .md sigue la guía de estilo

- [ ] Los resultados los genera el Make y los importa el LaTeX desde JSON, CSV, PNG, etc.

2021-02-11 19:59 UTC, evaristor requested changes
El GitHub Actions no está pasando

2021-02-11 21:15 UTC, evaristor requested changes
El reporte debe ser generado por Make en GitHub Actions.

2021-02-18 17:32 UTC, evaristor requested changes
Aquí te dejo mi primer tanda de comentarios

2021-02-18 17:32 UTC, evaristor commented on reports/herramientas.tex
> +\small{martha.paola.jimenez.martinez@uabc.edu.mx} \\
Por favor sólo usa tu correo de GECI

```suggestion
```

2021-02-18 17:32 UTC, evaristor commented on reports/herramientas.tex
> + \cite[( Rubio, J. 2020)]{ref1}.
Esta numeración consecutiva `ref1`, `ref2`, ... no es conveniete. Por favor usa nombres más descriptivos, por ejemplo `rubio_2020`. Busca un ejemplo del equipo

2021-03-02 20:06 UTC, evaristor commented
@MaritzaB ¿Cuál editor de texto usas?

2021-03-02 20:13 UTC, evaristor requested changes
- [ ] Algunas líneas exceden los 100 caracteres. Por favor podrías verificar que cada line tenga 100 o menos caracteres? Yo uso la extensión `stkb.rewrap` en VSCode.
- [ ] Las claves de las referencias (p.ej.: `BitAtlas`, `CanBlog`) usan abreviaturas. Por favor usa nombres más descriptivos sin abreviaturas.

2021-03-02 21:22 UTC, MaritzaB commented
> @MaritzaB ¿Cuál editor de texto usas?

Visual Studio Code... ¿Por qué? 🤔

2021-03-04 19:01 UTC, evaristor commented
> Visual Studio Code... ¿Por qué? thinking

😂😂😂
Me equivoqué; la pregunta era para @marthapaolajm

2021-03-04 19:35 UTC, marthapaolajm commented
> > Visual Studio Code... ¿Por qué? thinking
> 
> joyjoyjoy
> Me equivoqué; la pregunta era para @marthapaolajm

Jajajaja sí tambien uso Visual Studio Code 👀

2021-03-04 19:35 UTC, marthapaolajm commented
>     * [ ]  Algunas líneas exceden los 100 caracteres. Por favor podrías verificar que cada line tenga 100 o menos caracteres? Yo uso la extensión `stkb.rewrap` en VSCode.
> 
>     * [ x ]  Las claves de las referencias (p.ej.: `BitAtlas`, `CanBlog`) usan abreviaturas. Por favor usa nombres más descriptivos sin abreviaturas.

2021-03-04 19:52 UTC, marthapaolajm commented
>     * [x]  Algunas líneas exceden los 100 caracteres. Por favor podrías verificar que cada line tenga 100 o menos caracteres? Yo uso la extensión `stkb.rewrap` en VSCode.
> 
>     * [x]  Las claves de las referencias (p.ej.: `BitAtlas`, `CanBlog`) usan abreviaturas. Por favor usa nombres más descriptivos sin abreviaturas.

2021-03-08 21:38 UTC, evaristor requested changes
- [ ] Agrega párrafo introductorio donde expliques de que se trata el documento.
- [ ] Explica para que sirve cada cuentas que abriste.

2021-03-11 18:27 UTC, islasfernando requested changes
Hola Martha, aqui te dejo algunos comentarios del contenido. :v:

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +La ciencia de datos, explora datos para obtener conocimiento de ellos; lo que implica saber programación, estadística, comunicación, etc. Y para poder aplicar estos conocimientos, es esencial el domi
```suggestion
La ciencia de datos, explora datos para obtener conocimiento de ellos; lo que implica saber programación, estadística, comunicación, etc. Para poder aplicar estos conocimientos, es esencial el dominio de diversas plataformas, mostraremos algunas a continuación con su significado y su utilidad, así como algunos conceptos que forman parte de las herramientas necesarias para la ciencia de datos.
```

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +\title{\textbf{Tarea 0: Definiciones.}} \author{Martha Paola Jiménez
Creo que podemos ponerle **Tarea 1**. y puedes cambiarle el nombre, quiza: **Herramientas para Ciencia de Datos**, ó algo así.

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +programas del modo texto.
La parte de "ejecuta, una por una, las instrucciones introducidas por el usuario o contenidas en un script y devuelve los resultados." siento que cualquier lenguaje entra en esa descripción.

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +programas del modo texto.
```suggestion
BASH (Bourne Again SHell) es un intérprete de comandos que forma parte de las herramientas estándar de Linux. Es complatible con Shell. por lo cuq puedes correr scripts (.sh) sin modificación. En otras palabras, actúa como interfaz entre el kernel Linux y los usuarios o programas del modo texto.
```

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +entorno a otro, lo cual le permite optimizar sus aplicaciones para la nube.
```suggestion
\subsection*{Docker}
Es una tecnología de creación de contenedores que permite la creación y el uso
de contenedores. Sirve para usar los contenedores como máquinas
virtuales extremadamente livianas y modulares. Además, obtiene flexibilidad con
estos contenedores: puede crearlos, implementarlos, copiarlos y moverlos de un
entorno a otro, lo cual le permite optimizar sus aplicaciones para la nube.
```

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +entorno a otro, lo cual le permite optimizar sus aplicaciones para la nube.
Por Favor agrega un renglón donde digas que en nuestro equipo nos ayuda a asegurar la reproducibilidad de los resultados y no tener conflictos con las dependencias.

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +\citep{it_user_2020}
Creo que esto está mal, checa esta [liga](https://en.wikipedia.org/wiki/Data_cleansing). Puedes también tener un :tomato:  a Martiza para que te ayude con esta sección.

2021-03-11 18:27 UTC, islasfernando commented on reports/herramientas.tex
> +\item Gravatar (WordPress): Es una imagen reconocida globalmente, que te sigue por cada sitio web donde aparezca tu nombre.
En base al correo electrónico, más que el nombre.

2021-03-16 19:51 UTC, evaristor requested changes
- [ ] Creo que GitFlow, Análisis exploratorio de datos y Curación de datos no son herramientas, sino procedimientos. ¿Por favor podrías crear una nueva sección y mover estas tres subsecciones para allá?

2021-03-16 19:51 UTC, evaristor commented on reports/herramientas.tex
> +La ciencia de datos, explora datos para obtener conocimiento de ellos; lo que implica saber
¿Cree que podríamos prescindir de esta coma?
```suggestion
La ciencia de datos explora datos para obtener conocimiento de ellos; lo que implica saber
```

2021-03-17 17:50 UTC, MaritzaB requested changes
Hola @marthapaolajm ✌🏽 Uffff tu reporte va que vuela 🏇!  Muchas felicidades 🥳, parece que ya son bastantes cosas las que has aprendido 🤓.
El reporte está bastante completo. Has citado bastantes referencias y eso es algo bueno, ya que has investigado mucho acerca de todos los temas. Sin embargo, algo que me gustaría ver es más tu percepción de las cosas que has aprendido, tal vez rematar al final de casa sección con un pequeño párrafo de tus propias palabras 💬. Eso también te ayudará a clarificar tus ideas 💭 y a asimilar todo este conocimiento.

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +sea más fácil para los individuos y equipos usar Git como la versión de control y colaboración.
Siento que en la parte de _versión de control_ más bien se refiere al _control de versión_ ... 🤔
¿Será que queda mejor de esta forma? 
```suggestion
Sirve como un servicio de hosting de repositorios almacenados en la nube. Esencialmente, hace que
sea más fácil para los individuos y equipos usar Git como el sistema de control versiones y colaboración.
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +planificación de entregas iterativas. Permite la paralelización del desarrollo mediante ramas
```suggestion
Es un flujo de trabajo aplicado a un repositorio Git. Sirve para que los proyectos lleven una
planificación de entregas iterativas. Permite la paralelización del desarrollo mediante ramas
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +soporta la reparación de errores en cualquier momento.
¿Qué te parecen la siguiente opción?

```suggestion
independientes para la preparación, mantenimiento y publicación de versiones del proyecto así como
la reparación de errores en cualquier momento.
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +diversos modelos de desarrollo, por lo que no exige un estilo único de programación.
```suggestion
Sirve para interpretar el código del programador, donde a su vez lo traduce y ejecuta. Utiliza
diversos modelos de desarrollo, por lo que no exige un estilo único de programación.
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +como la ejecución de código a través del navegador en múltiples lenguajes.
```suggestion
Es una interfaz web de código abierto que permite la inclusión de texto, vídeo, audio, imágenes, así
como la ejecución de código a través del navegador en múltiples lenguajes. 
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +comportamiento así como también apartamentos importantes al modelo subyacente.
No estoy segura de como podemos mejorar esta parte, pero me causa conflicto la frase _organizar la información que nos dan los datos de manera de detectar algún patrón de comportamiento_ 😵, ¿podrías por favor explicarla un poco más?, para así poder hacer una sugerencia de edición 🙏.
También podrías explicar a qué te refieres con _apartamentos importantes al modelo subyacente_ por fis? 😊
Por último, la frase _así como también_ es bastante redundante, yo te recomiendo escoger ya sea _así como_ ó _también_ 😉.
```suggestion
Ayuda a organizar la información que nos dan los datos de manera de detectar algún patrón de
comportamiento así como apartamentos importantes al modelo subyacente.
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +Es decir, hay errores estructurales y de contenido.
Me parece que está muy bien la idea. Solo hay que trabajar un poco más la explicación. ¿Qué te parece la siguiente sugerencia?
Al final puedes agregar algunos ejemplos de cada tipo de error 🤭 ¿qué opinas?

```suggestion
Es un procedimiento que consiste en la detección y eliminación de errores en los datos de monitoreo que son capturados por personal de campo en las islas.  Cuando se toman los datos
puede haber errores estructurales y errores de contenido.
Ejemplos de errores estructurales son:
Ejemplos de errores de contenido son:
```

2021-03-17 17:50 UTC, MaritzaB commented on reports/herramientas.tex
> +Las bitacoras son transcritos a formato de tabla (.xlsx). El curador de datos es el encargado de
Por aquí hay un errorcillo de [concordancia nominal](https://es.wikipedia.org/wiki/Concordancia_gramatical#Concordancia_nominal).
¿Que te parece si ponemos el rol de _curador de datos_ de forma inclusiva 👨‍💻 👩‍💻?
```suggestion
Las bitacoras son transcritas a formato de tabla (.xlsx). La o el curador de datos es el encargado de
```

2021-03-18 18:56 UTC, marthapaolajm commented on reports/herramientas.tex
> +La ciencia de datos, explora datos para obtener conocimiento de ellos; lo que implica saber
¡Claro que sí!

2021-03-18 18:59 UTC, marthapaolajm commented on reports/herramientas.tex
> +soporta la reparación de errores en cualquier momento.
Sí, tambien me gusta más como suena. ¡Muchas gracias Maritza!

2021-03-18 20:50 UTC, marthapaolajm commented on reports/herramientas.tex
> +Las bitacoras son transcritos a formato de tabla (.xlsx). El curador de datos es el encargado de
¡Sí! me parece perfecto, gracias✨

2021-03-18 20:51 UTC, marthapaolajm commented on reports/herramientas.tex
> +sea más fácil para los individuos y equipos usar Git como la versión de control y colaboración.
Sí muy bien!

2021-03-18 20:54 UTC, marthapaolajm commented on reports/herramientas.tex
> +comportamiento así como también apartamentos importantes al modelo subyacente.
Muy bien, muchas gracias 🙌 🤩

2021-03-18 20:56 UTC, marthapaolajm commented on reports/herramientas.tex
> +Es decir, hay errores estructurales y de contenido.
Sí, me gusto para agregar ejemplos 🎉

2021-03-18 20:57 UTC, marthapaolajm commented on reports/herramientas.tex
> +dependencias.
Sí claro!

2021-03-23 21:23 UTC, evaristor requested changes
Ahí va...

2021-03-23 21:23 UTC, evaristor commented on reports/herramientas.tex
> +dominio de diversas plataformas, mostraremos algunas a continuación con su significado y su
[Nuestra guía](https://islasgeci.github.io/guia_de_estilo/prosa) de estilo dice:

> Prefiere enunciados cortos para ganar legibilidad (20-25 palabras)

El enunciado siguiente tiene 37 palabras:

> Para poder aplicar estos conocimientos,es esencial el dominio de diversas plataformas, mostraremos algunas a continuación con susignificado y su utilidad, así como algunos conceptos que forman parte de las herramientasnecesarias para la ciencia de datos.

Por favor separa ese enunciado en enunciados más cortos.

2021-03-23 21:23 UTC, evaristor commented on reports/herramientas.tex
> +Es decir, Git lleva el registro de cada cambio hecho, incluso arregla cambios hechos por diferentes personas en archivos compartidos.
Parece que esta línea y otras exceden los 100 caracteres.

2021-03-23 21:23 UTC, evaristor commented on reports/herramientas.tex
> +\subsection*{GitFlow}
En una revisión anterior te pedí que movieras GitFlow a la sección de Procedimientos. ¿Por favor lo podrías hacer?

2021-03-23 21:23 UTC, evaristor commented on Dockerfile
> +CMD make
¿Son estas líneas necesarias? Pensé que ya estaban definidas dentro de `islasgeci/base`.

2021-03-24 22:59 UTC, MaritzaB requested changes
Hola @marthapaolajm, te dejo unos comentarios. Si tienes algunas dudas podemos hacer 🍅 😄 .

2021-03-24 22:59 UTC, MaritzaB commented on reports/herramientas.tex
> +Así pues Python está listo para realizar cualquier tipo de programa, desde una página web, hasta una aplicación de windows.
Creo aquí falta una coma.
```suggestion
Así pues, Python está listo para realizar cualquier tipo de programa, desde una página web, hasta una aplicación de windows.
```

2021-03-24 22:59 UTC, MaritzaB commented on reports/herramientas.tex
> +Ejemplos de errores estructurales son: Celdas en blanco, alguna parte del texto no esté plano, datos duplicados, etc.
Creo que está confuso lo de "alguna parte del texto no esté plano". 
Mañana podemos hacer un 🍅 para aclararlo y agregar algunos otros ejemplos 😉 .

2021-03-25 19:13 UTC, marthapaolajm commented on reports/herramientas.tex
> +\subsection*{GitFlow}
Claro que sí, una disulpa se me paso

2021-04-05 17:35 UTC, MaritzaB commented on reports/herramientas.tex
> +\subsection*{Curacion de datos}
```suggestion
\subsection*{Curación de datos}
```

2021-04-05 17:35 UTC, MaritzaB commented on Dockerfile
> +CMD make
Hola @marthapaolajm, creo que todavía está pendiente este comentario. Una forma en la que puedes verificar si aún son necesarias estas líneas es eliminarlas y reconstruir el contenedor, si vuelves a generar el reporte y todo sale bien entonces ya no las necesitamos 😉 . Igual si tienes alguna duda podemos hacer un 🍅.

2021-04-05 17:35 UTC, MaritzaB commented on reports/herramientas.tex
> + \cite[( Rubio, J. 2020)]{ref1}.
@marthapaolajm con respecto a este comentario, creo que lo que nos conviene es que desde el archivo .bib de las referencias cambies el nombre de `{ref1}`a algo más descriptivo.
Aquí te pongo un ejemplo que usamos en el equipo.
En el archivo .bib esta es nuestra referencia y en vez de ponerle `ref1` le pusimos `scikit-learn` que es un nombre más descriptivo de la cita.
```
@article{scikit-learn,
 title={Scikit-learn: Machine Learning in {P}ython},
 author={Pedregosa, F. and Varoquaux, G. and Gramfort, A. and Michel, V.
         and Thirion, B. and Grisel, O. and Blondel, M. and Prettenhofer, P.
         and Weiss, R. and Dubourg, V. and Vanderplas, J. and Passos, A. and
         Cournapeau, D. and Brucher, M. and Perrot, M. and Duchesnay, E.},
 journal={Journal of Machine Learning Research},
 volume={12},
 pages={2825--2830},
 year={2011}
}
```
En el reporte lo llamamos de esta forma:
```
Para conocer más al respecto véase la sitio web de 
\href{https://scikit-learn.org/stable/modules/density.html#kernel-density}{{\color{blue}\textit{\underline{scikit learn}}}} 
\cite{scikit-learn}.
```

2021-04-05 17:35 UTC, MaritzaB commented on reports/herramientas.tex
> +\subsection*{GitFlow}
Creo que todavía hace falta crea una sección de procedimientos como la sección de herramientas.
Algo como:
```
\section*{Procedimientos}
```

2021-04-05 17:35 UTC, MaritzaB commented on reports/herramientas.tex
> +Sirve para interpretar el c\'odigo del programador, donde a su vez lo traduce y ejecuta. Y utiliza diversos modelos de desarrollo, por lo que no exige un estilo \'unico de programaci\'on.
```suggestion
Sirve para interpretar el c\'odigo del programador, donde a su vez lo traduce y ejecuta. Utiliza diversos modelos de desarrollo, por lo que no exige un estilo \'unico de programaci\'on.
```

2021-04-05 17:35 UTC, MaritzaB commented on reports/herramientas.tex
> +\item Depuraci\'on de datos: distinguir entre los datos que son importantes y los que no lo son al ejecutar un an\'alisis de big data.
Creo que ya habíamos encontrado una forma en la que pudieras poner acentos sin tener que poner `\'`, ¿no? 🤔 
Esto con el fin de que podamos escribir los acentos de la siguiente forma:
```suggestion
\item Depuración de datos: distinguir entre los datos que son importantes y los que no lo son al ejecutar un análisis de big data.
```

2021-04-05 17:35 UTC, MaritzaB commented on reports/herramientas.tex
> +Ayudan a organizar la informaci\'on que nos dan los datos de manera de detectar alg\'un patr\'on de comportamiento as\'i como tambi\'en apartamentos importantes al modelo subyacente.
La frase _así como también_ es redundante. ¿Podrías por favor escoger _así como_ o _tambien_ por favor?
Creo que también ya lo había puesto en un comentario en una revisión anterior, pero por favor podrías explicar a qué te refieres con "_apartamentos importantes al modelo subyacente_"?
```suggestion
Ayudan a organizar la informaci\'on que nos dan los datos de manera de detectar alg\'un patr\'on de comportamiento as\'i como apartamentos importantes al modelo subyacente.
```

2021-04-05 17:37 UTC, MaritzaB requested changes
@marthapaolajm creo que algo pasó con el Pull request. Me da la sensación de que estoy revisando algo obsoleto. 🤔

2021-04-07 22:21 UTC, MaritzaB requested changes
Hola @marthapaolajm, vi que ya quedaron atendidos los comentarios 🙌🏽 .
Solo dejó ahí unas sugerencias menores 😉.
Algo pasó en la revisión anterior que estaba viendo una versión obsoleta del reporte, pero ya está bien jeje.

2021-04-07 22:21 UTC, MaritzaB commented on reports/herramientas.tex
> +en el \href{https://drive.google.com/drive/folders/1X-EdWtD6sxItwKmCyGpviCt85IvexRxo}{manual de
```suggestion
coherente, no haya datos duplicados, ni espacios en blanco, etc. Siguiendo una estructura definida
de acuerdo al \href{https://drive.google.com/drive/folders/1X-EdWtD6sxItwKmCyGpviCt85IvexRxo}{manual de
```

2021-04-07 22:21 UTC, MaritzaB commented on reports/herramientas.tex
> +
```suggestion
```

2021-04-08 18:34 UTC, islasfernando approved these changes
Excelente @marthapaolajm se ve muy bien el reporte! Excelente trabajo 🎉 🎈

2021-04-08 18:37 UTC, merged