GECI-53: Revisión postentrega
IslasGECI/ejemplo_para_martha pull request #4
Opened 2021-05-05 16:42 UTC by analislas

2021-05-05 16:59 UTC, evaristor requested changes
- [ ] En el encabezado de la tabla 1, incluye el nombre científico de la especie entre paréntesis e itálicas junto al nombre común.
- [ ] En el encabezado de la tabla 1, quita las itálicas de _min_ y _max_
- [ ] La cantidad de recistros son números enteros. Por favor podrías quitar el ".0"?
- [ ] En la forma actial de la tabla, la columna total me causa problemas. ¿El promedio total es promedio mezclando gramos con centímetros? También el renglón N me causa problemas porque no comparte las mismas unidades que el resto de los estadísticos en las colimnas. ¿Por favor podrías incluir una tabla transpuesta (variables en los renglones y estadístocos en las columnas) para elegir la más conveniente?
- [ ] Por favor mueve los pies de figura hacia abajo de la figuras. (El encabezado de las tablas está bien arriba de las tablas.)

2021-05-07 20:31 UTC, marthapaolajm commented
>     * [x]  En el encabezado de la tabla 1, incluye el nombre científico de la especie entre paréntesis e itálicas junto al nombre común.
> 
>     * [x]  En el encabezado de la tabla 1, quita las itálicas de _min_ y _max_
> 
>     * [ ]  La cantidad de recistros son números enteros. Por favor podrías quitar el ".0"?
> 
>     * [ ]  En la forma actial de la tabla, la columna total me causa problemas. ¿El promedio total es promedio mezclando gramos con centímetros? También el renglón N me causa problemas porque no comparte las mismas unidades que el resto de los estadísticos en las colimnas. ¿Por favor podrías incluir una tabla transpuesta (variables en los renglones y estadístocos en las columnas) para elegir la más conveniente?
> 
>     * [x]  Por favor mueve los pies de figura hacia abajo de la figuras. (El encabezado de las tablas está bien arriba de las tablas.)

2021-05-07 20:36 UTC, marthapaolajm commented
- [x]  En el encabezado de la tabla 1, incluye el nombre científico de la especie entre paréntesis e itálicas junto al nombre común.
- [x]  En el encabezado de la tabla 1, quita las itálicas de _min_ y _max_
- [ ]  La cantidad de recistros son números enteros. Por favor podrías quitar el ".0"?
- [ ]  También el renglón N me causa problemas porque no comparte las mismas unidades que el resto de los estadísticos en las colimnas. ¿Por favor podrías incluir una tabla transpuesta (variables en los renglones y estadístocos en las columnas) para elegir la más conveniente?
-  [x]  Por favor mueve los pies de figura hacia abajo de la figuras. (El encabezado de las tablas está bien arriba de las tablas.)

2021-05-07 20:57 UTC, marthapaolajm commented
En el punto cuatro que dices que estamos combinando unidades, no es prometió total, es longitud total. Tal vez no se logra visualizar bien, ya que pusimos la longitud que sale en arriba en medio de las longitudes que son, para no tener que repetir longitud tres veces y que la tabla no saliera tan larga 😃

2021-05-20 18:19 UTC, closed without merging

2021-05-21 18:12 UTC, marthapaolajm commented
> ```
> git clone https://github.com/marthapaolajm/ejemplo_para_martha.git
> cd ejemplo_para_martha
> git checkout develop
> docker build --tag ejemplo_para_martha .
> docker run --volume ${PWD}:/workdir --env BITBUCKET_USERNAME="${BITBUCKET_USERNAME}" --env BITBUCKET_PASSWORD="${BITBUCKET_PASSWORD}" ejemplo_para_martha make
> xdg-open reports/aed_serpientes_isla_isabel.pdf
> ```
> 
* [x]   En el encabezado de la tabla 1, incluye el nombre científico de la especie entre paréntesis e itálicas junto al nombre común.
 
* [x]  En el encabezado de la tabla 1, quita las itálicas de _min_ y _max_
 
* [x]  La cantidad de recistros son números enteros. Por favor podrías quitar el ".0"?
 
* [x]  En la forma actial de la tabla, la columna total me causa problemas. ¿El promedio total es promedio mezclando gramos con centímetros? También el renglón N me causa problemas porque no comparte las mismas unidades que el resto de los estadísticos en las colimnas. ¿Por favor podrías incluir una tabla transpuesta (variables en los renglones y estadístocos en las columnas) para elegir la más conveniente?
 
* [x]  Por favor mueve los pies de figura hacia abajo de la figuras. (El encabezado de las tablas está bien arriba de las tablas.)
 
* [GECI-53: Análisis exploratorio de datos de serpientes en Isla Isabel](https://app.gitkraken.com/glo/card/11df004f0b34480a938bbce7351efa9f)