Contenido Reporte
IslasGECI/ejemplo_para_martha pull request #6
Opened 2021-06-09 14:29 UTC by marthapaolajm

## Contenido siguiendo la guía de [Estilo en la prosa](https://islasgeci.github.io/guia_de_estilo/prosa)

- [ ] Utiliza lenguaje inclusivo
- [ ] `geci-testmake` genera el reporte
Los pies de las figuras y los encabezados de las tablas incluyen:
- [ ] Nombre de las variables
- [ ] Unidades de las variabels
- [ ] Especie o grupo biológico
- [ ] Isla o región geográfico
- [ ] Temporada o intervalo de tiempo
- [ ] Preferimos la voz activa sobre la voz pasiva
- [ ] Prefiere enunciados cortos para ganar legibilidad (20-25 palabras)

2021-06-17 15:44 UTC, evaristor requested changes
Ahí te va una revisión rápida.

- [ ] Además de la islas, por favor también agrega al título la especie y el periodo.
- [ ] Parece que hace falta alguna puntuación después de 2014 en: _"Monitoreo de falsa coralillo en isla Isabel desde 2008 hasta 2014 Esta base de datos contiene"_
- [ ] El nombre científico (_Lamprompeltis triangulum_) es en itálicas

2021-06-17 19:05 UTC, marthapaolajm commented
> Ahí te va una revisión rápida.
>  - [x]  Además de la islas, por favor también agrega al título la especie y el periodo.
>
>  -  [x]  Parece que hace falta alguna puntuación después de 2014 en: _"Monitoreo de falsa coralillo en isla Isabel desde 2008 hasta 2014 Esta base de datos contiene"_
>
>    * [ ]  El nombre científico (_Lamprompeltis triangulum_) es en itálicas

El último punto no se logró resolver porque la descripción viene del datapackage.json

2021-06-17 19:19 UTC, evaristor requested changes
- [ ] Al título le falta un _"de"_
![image](https://user-images.githubusercontent.com/3461018/122459403-c1807580-cf65-11eb-92b3-8a7f9f7926db.png)

- [ ] El nombre científico va en itálicas
![image](https://user-images.githubusercontent.com/3461018/122459265-9433c780-cf65-11eb-813c-efad10755a42.png)

- [ ] No se ve el número de la Figura
![image](https://user-images.githubusercontent.com/3461018/122459728-1b813b00-cf66-11eb-8b62-791fa170c02d.png)

2021-06-17 19:49 UTC, nepito requested changes
Hola @marthapaolajm aquí te dejó mi revisión 🖖🏿

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +periodo de 2008 al 2014. Incluimos la disponibilidad de datos; la cual esta representada mediante la
Error de dedo:
```suggestion
periodo de 2008 al 2014. Incluimos la disponibilidad de datos; la cual está representada mediante la
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +delimitada por $(Q_1)$ y $(Q_3)$, donde la línea naranja de las cajas; es la mediana $(Q_2)$. Y los
Creo que le sobra un punto y coma:
```suggestion
delimitada por $(Q_1)$ y $(Q_3)$, donde la línea naranja de las cajas es la mediana $(Q_2)$. Y los
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +la canidad de registros, $\bar{\delta}$ es el promedio, $\sigma$ es la desviacion estandar, min es
Error de dedo y faltaron un par de tildes:
```suggestion
la cantidad de registros, $\bar{\delta}$ es el promedio, $\sigma$ es la desviación estándar, min es
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +el minimo, max es el maximo y $Q_1$, $Q_2$ y $Q_3$ son los cuartiles uno, dos y tres
Faltaron algunas tildes:
```suggestion
el mínimo, max es el máximo y $Q_1$, $Q_2$ y $Q_3$ son los cuartiles uno, dos y tres
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
>  temporada de la longitud cloaca cola, de los individuos de falsa coralillo capturados en la Isla
Acostumbramos usar dos opciones para referirnos a una islas:
1. Como si fuera nombre propio la escribimos sin artículo "capturados en ~la~ Isla Isabel"
1. Como sustantivo, agregamos artículo y escribimos isla en minúscula "capturados en la ~I~isla Isabel"

A mí me gusta más la segunda opción, pero todos prefieren la primera. Por favor escoge alguna de las dos. 
```suggestion
temporada de la longitud cloaca cola, de los individuos de falsa coralillo capturados en Isla
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +mucha variacion en la mediana. Con una mediana en promedio de 10.7 cm y una variación de 7.6 cm a
Faltó una tilde:
```suggestion
mucha variación en la mediana. Con una mediana en promedio de 10.7 cm y una variación de 7.6 cm a
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
>  temporada de la longitud hocico cola, de los individuos de falsa coralillo capturados en la Isla
Decide un lado o estás conmigo en mi contra 😂🤣😂🤣:
```suggestion
temporada de la longitud hocico cola, de los individuos de falsa coralillo capturados en Isla
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +de la longitud total, de los individuos de falsa coralillo capturados en la Isla Isabel con datos
Por favor quita el artículo:
```suggestion
de la longitud total, de los individuos de falsa coralillo capturados en Isla Isabel con datos
```

2021-06-17 19:49 UTC, nepito commented on reports/aed_serpientes_isla_isabel.tex
> +masa, de los individuos de falsa coralillo capturados en la Isla Isabel con datos del 2008 a 2014.
Por favor quita el artículo "la":
```suggestion
masa, de los individuos de falsa coralillo capturados en Isla Isabel con datos del 2008 a 2014.
```

2021-06-18 17:44 UTC, marthapaolajm commented on reports/aed_serpientes_isla_isabel.tex
>  temporada de la longitud cloaca cola, de los individuos de falsa coralillo capturados en la Isla
Muchas gracias por la explicacón me fue de mucha ayuda  🙌

2021-06-18 17:47 UTC, marthapaolajm commented on reports/aed_serpientes_isla_isabel.tex
>  temporada de la longitud hocico cola, de los individuos de falsa coralillo capturados en la Isla
EStoy contigo  😅

2021-06-18 17:52 UTC, marthapaolajm commented
>    - [x]  Al título le falta un _"de"_
>       ![image](https://user-images.githubusercontent.com/3461018/122459403-c1807580-cf65-11eb-92b3-8a7f9f7926db.png)
> 
>    - [x]  No se ve el número de la Figura
>       ![image](https://user-images.githubusercontent.com/3461018/122459728-1b813b00-cf66-11eb-8b62-791fa170c02d.png)

2021-06-18 17:53 UTC, marthapaolajm commented
Muchas gracias Nepo  🙌 😁

2021-06-18 18:09 UTC, evaristor approved these changes
![lgtm](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

2021-06-22 18:29 UTC, nepito requested changes
Aquí te dejo un par de observaciones

2021-06-22 19:58 UTC, marthapaolajm commented
Gracias Nepo! raised_hands

2021-06-23 17:12 UTC, MaritzaB requested changes
Hola @marthapaolajm, se ve bastante bien el reporte 👌🏽 , solo te dejo algunos comentarios 😄.
Saludos.

2021-06-23 17:12 UTC, MaritzaB commented on reports/aed_serpientes_isla_isabel.tex
>  \caption{Diagrama de cajas por temporada de la longitud total, de los individuos de falsa coralillo capturados en la Isla Isabel con datos del 2008 a 2011. En las temporadas 2008 y 2009 se obtienen d
La expresión "así también" es redundante.
¿En la última oración quieres decir que tambien 2008 y 2011 son atípicos? Si es así, entonces talvez quedaría mejor de la siguiente manera:
```suggestion
\caption{Diagrama de cajas por temporada de la longitud total, de los individuos de falsa coralillo capturados en Isla Isabel con datos del 2008 a 2011. En las temporadas 2008, 2009 y 2011 obtuvimos datos atípicos, siendo en 2008 y 2011 ambas medianas más cercanas al cuartil tres.}
```
¿Qué opinas? 🤔

2021-06-23 17:12 UTC, MaritzaB commented on reports/aed_serpientes_isla_isabel.tex
> +consistente.
```suggestion
En la Figura \ref{fig:pngBoxsplotMasa} podemos observar un diagrama de cajas por cada temporada de 2008 a 2014, de la masa de individuos de falsa coralillo capturados en Isla Isabel.
Comparando los diagramas de las siete temporadas, observamos  que la variación de las medianas no es
consistente.
```

2021-06-24 16:46 UTC, marthapaolajm commented on reports/aed_serpientes_isla_isabel.tex
> +el mínimo, max es el máximo y $Q_1$, $Q_2$ y $Q_3$ son los cuartiles uno, dos y tres
Sii, muchas gracias Maritza!!

2021-06-24 16:47 UTC, marthapaolajm commented on reports/aed_serpientes_isla_isabel.tex
> +del 2008 a 2011. Se observa que las medianas de las cuatro temporadas, son consistentes.
Sí, me gusta más ¡Muchas gracias!

2021-06-24 17:02 UTC, marthapaolajm commented on reports/aed_serpientes_isla_isabel.tex
>  \caption{Diagrama de cajas por temporada de la longitud total, de los individuos de falsa coralillo capturados en la Isla Isabel con datos del 2008 a 2011. En las temporadas 2008 y 2009 se obtienen d
Sí eso quería decir, muchas gracias!!

2021-06-24 17:15 UTC, marthapaolajm commented
Muchas gracias Maritza!! 😁

2021-06-25 01:53 UTC, MaritzaB requested changes
@marthapaolajm muchas gracias por atender las sugerencias. Yo creo que ya casí queda, solo falta agregar referencias al reporte y creo que con eso ya queda 🙌🏽 .

2021-06-25 20:01 UTC, marthapaolajm commented
Gracias a ti Maritza!🙌🏽 , le agregamos como referencia la descripción de análisis de datos de GECI, ya que no utilizamos otra fuente bibliografica. ¿Se te ocurre alguna otra fuente que pueda referenciar?  😄

2021-06-25 20:36 UTC, MaritzaB approved these changes
Súper @MaritzaB muchas gracias por agregar la referencia, yo creo que esa está bien.
Está muy bonito tu reporte 🌟, ¡muchas felicidades!

2021-06-25 20:51 UTC, merged